-- AlterTable
ALTER TABLE `transactions` MODIFY COLUMN `type` ENUM(
  'DEPOSIT',
  'WITHDRAWAL',
  'PROFIT_DISTRIBUTION',
  'PACKAGE_RETURN',
  'PACKAGE_PURCHASE',
  'REFERRAL_BONUS_ADDED',
  'GIFT'
) NOT NULL;
